import log from "./index"

log.gray(`gray`)
log.red(`red`)
log.green(`green`)
log.yellow(`yellow`)
log.blue(`blue`)
log.magenta(`magenta`)
log.cyan(`cyan`)
log.success(`success`)
log.error(`error`)
log.warn(`warn`)
log.info(`info`)
log(`log`)
// log.clear()